[project]
name = "edumotion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "debugpy>=1.8.13",
    "log-symbols>=0.0.14",
    "numpy>=2.2.4",
    "pytest-benchmark>=5.1.0",
    "vprof>=0.38",
]
